const DEFAULT_REMINDER_MIN = 10

export type IcsTimeMode = 'local' | 'utc'

export type IcsAlarm = {
  minutesBefore: number
  description?: string
}

export type IcsRecurrence = {
  frequency: 'DAILY' | 'WEEKLY' | 'MONTHLY' | 'YEARLY'
  interval?: number
  count?: number
  until?: Date
}

export type IcsCalendarEvent = {
  title: string
  start: Date
  end?: Date
  timeMode?: IcsTimeMode
  uid?: string
  description?: string
  location?: string
  categories?: string[]
  alarms?: IcsAlarm[]
  /** Backward-compatible single-alarm input. Prefer alarms for new exporters. */
  remindMinutes?: number
  recurrence?: IcsRecurrence
}

export type IcsCalendarOptions = {
  name?: string
  description?: string
  groupId?: string
  defaultReminderMin?: number | null
  generatedAt?: Date
}

export function downloadICS(filename: string, ics: string) {
  if (typeof document === 'undefined') return
  const blob = new Blob([ics], { type: 'text/calendar;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const link = document.createElement('a')
  link.href = url
  link.download = filename
  link.hidden = true
  document.body.appendChild(link)
  link.click()
  link.remove()
  window.setTimeout(() => URL.revokeObjectURL(url), 0)
}

export function buildIcsCalendar(events: IcsCalendarEvent[], opts: IcsCalendarOptions = {}) {
  const name = opts.name ?? 'Athan Reminders'
  const groupId = opts.groupId ?? 'ATHAN-PWA'
  const defaultReminderMin = opts.defaultReminderMin === undefined ? DEFAULT_REMINDER_MIN : opts.defaultReminderMin
  const generatedAt = formatUtcTimestamp(opts.generatedAt ?? new Date())
  const seenUids = new Map<string, number>()
  const lines = [
    'BEGIN:VCALENDAR',
    'VERSION:2.0',
    `PRODID:-//Athan PWA//${escapeIcsText(groupId)}//EN`,
    'CALSCALE:GREGORIAN',
    'METHOD:PUBLISH',
    `X-WR-CALNAME:${escapeIcsText(name)}`,
    `X-WR-CALDESC:${escapeIcsText(opts.description ?? `${name} - generated by Athan PWA`)}`
  ]

  events.forEach((event) => {
    const timeMode = event.timeMode ?? 'local'
    const end = event.end ?? new Date(event.start.getTime() + 5 * 60 * 1000)
    const baseUid = sanitizeUid(event.uid || makeStableUid(event, groupId))
    const duplicateNumber = (seenUids.get(baseUid) ?? 0) + 1
    seenUids.set(baseUid, duplicateNumber)
    const uid = duplicateNumber === 1 ? baseUid : withUidSuffix(baseUid, duplicateNumber)
    const categories = Array.from(new Set([...(event.categories ?? []), groupId, 'Athan-PWA']))
    const alarms = event.alarms ?? (
      event.remindMinutes !== undefined
        ? [{ minutesBefore: event.remindMinutes }]
        : defaultReminderMin === null
          ? []
          : [{ minutesBefore: defaultReminderMin }]
    )

    lines.push(
      'BEGIN:VEVENT',
      `UID:${escapeIcsText(uid)}`,
      `DTSTAMP:${generatedAt}`,
      `DTSTART:${formatTimestamp(event.start, timeMode)}`,
      `DTEND:${formatTimestamp(end, timeMode)}`,
      `SUMMARY:${escapeIcsText(event.title)}`,
      `CATEGORIES:${categories.map(escapeIcsText).join(',')}`,
      `X-ATHAN-GROUP:${escapeIcsText(groupId)}`
    )

    if (event.description) lines.push(`DESCRIPTION:${escapeIcsText(event.description)}`)
    if (event.location) lines.push(`LOCATION:${escapeIcsText(event.location)}`)
    if (event.recurrence) lines.push(buildRecurrenceRule(event.recurrence))

    for (const alarm of alarms) {
      const minutes = normalizeReminder(alarm.minutesBefore)
      lines.push(
        'BEGIN:VALARM',
        `TRIGGER:${minutes === 0 ? 'PT0M' : `-PT${minutes}M`}`,
        'ACTION:DISPLAY',
        `DESCRIPTION:${escapeIcsText(alarm.description ?? event.title)}`,
        'END:VALARM'
      )
    }
    lines.push('END:VEVENT')
  })

  lines.push('END:VCALENDAR')
  return lines.map(foldIcsLine).join('\r\n')
}

type IcsItem = {
  title: string
  when: Date
  /** Minutes before the event to trigger a popup reminder. Default 10. */
  remindMinutes?: number
  /** Optional custom text to append to SUMMARY (overrides default "(X min before)"). */
  summarySuffix?: string
}

export function buildIcsForDates(
  items: IcsItem[],
  name = 'Athan Reminders',
  groupId = 'ATHAN-PWA',
  defaultReminderMin = DEFAULT_REMINDER_MIN
) {
  return buildIcsCalendar(items.map((item) => {
    const minutes = item.remindMinutes === undefined ? defaultReminderMin : normalizeReminder(item.remindMinutes)
    const suffix = typeof item.summarySuffix === 'string' ? item.summarySuffix : `(${minutes} min before)`
    return {
      title: `${item.title}${suffix ? ` ${suffix}` : ''}`,
      start: item.when,
      end: new Date(item.when.getTime() + 5 * 60 * 1000),
      uid: `${formatLocalTimestamp(item.when)}-${slug(item.title)}@${groupId.toLowerCase()}`,
      description: item.title,
      categories: [groupId],
      alarms: [{ minutesBefore: minutes }]
    }
  }), {
    name,
    description: `${name} - generated by Athan PWA`,
    groupId,
    defaultReminderMin
  })
}

export type DayPrayers = {
  fajr: Date
  sunrise: Date
  dhuhr: Date
  asr: Date
  maghrib: Date
  isha: Date
}

export function buildIcsForPrayerDay(
  day: DayPrayers,
  offsetMinInput: number,
  opts?: {
    ishaFixedTime?: string
    name?: string
    groupId?: string
    defaultReminderMin?: number
  }
) {
  return buildIcsForDates(
    prayerItemsForDay(day, offsetMinInput, opts?.ishaFixedTime, opts?.defaultReminderMin ?? DEFAULT_REMINDER_MIN),
    opts?.name ?? 'Athan Reminders',
    opts?.groupId ?? 'ATHAN-PWA',
    opts?.defaultReminderMin ?? DEFAULT_REMINDER_MIN
  )
}

export function buildIcsForWeek(
  days: DayPrayers[],
  offsetMinInput: number,
  opts?: {
    ishaFixedTime?: string
    name?: string
    groupId?: string
    defaultReminderMin?: number
  }
) {
  const name = opts?.name ?? 'Athan Reminders'
  const groupId = opts?.groupId ?? 'ATHAN-PWA'
  const defaultReminderMin = opts?.defaultReminderMin ?? DEFAULT_REMINDER_MIN
  return buildIcsForDates(
    days.flatMap((day) => prayerItemsForDay(day, offsetMinInput, opts?.ishaFixedTime, defaultReminderMin)),
    name,
    groupId,
    defaultReminderMin
  )
}

function prayerItemsForDay(day: DayPrayers, offsetMinInput: number, ishaFixedTime: string | undefined, reminderMinutes: number): IcsItem[] {
  const offsetMin = Math.max(1, Math.floor(offsetMinInput || 0))
  const minus = (date: Date, minutes: number) => new Date(date.getTime() - minutes * 60 * 1000)
  const items: IcsItem[] = [
    { title: 'Fajr', when: day.fajr },
    { title: 'Sunrise', when: day.sunrise },
    { title: 'Dhuhr', when: day.dhuhr },
    { title: 'Asr', when: day.asr },
    { title: 'Maghrib', when: day.maghrib },
    { title: 'Isha', when: day.isha },
    { title: `Fajr reminder before Sunrise (${offsetMin}m)`, when: minus(day.sunrise, offsetMin), remindMinutes: reminderMinutes, summarySuffix: '' },
    { title: `Dhuhr reminder before Asr (${offsetMin}m)`, when: minus(day.asr, offsetMin), remindMinutes: reminderMinutes, summarySuffix: '' },
    { title: `Asr reminder before Maghrib (${offsetMin}m)`, when: minus(day.maghrib, offsetMin), remindMinutes: reminderMinutes, summarySuffix: '' },
    { title: `Maghrib reminder before Isha (${offsetMin}m)`, when: minus(day.isha, offsetMin), remindMinutes: reminderMinutes, summarySuffix: '' }
  ]

  if (ishaFixedTime) {
    const [hours, minutes] = ishaFixedTime.split(':').map(Number)
    if (Number.isInteger(hours) && Number.isInteger(minutes) && hours >= 0 && hours <= 23 && minutes >= 0 && minutes <= 59) {
      const customIsha = new Date(day.isha)
      customIsha.setHours(hours, minutes, 0, 0)
      items.push({ title: 'Isha (custom reminder)', when: customIsha, remindMinutes: reminderMinutes, summarySuffix: '' })
    }
  }
  return items
}

function formatTimestamp(date: Date, mode: IcsTimeMode) {
  return mode === 'utc' ? formatUtcTimestamp(date) : formatLocalTimestamp(date)
}

function formatLocalTimestamp(date: Date) {
  return `${date.getFullYear()}${pad(date.getMonth() + 1)}${pad(date.getDate())}T${pad(date.getHours())}${pad(date.getMinutes())}${pad(date.getSeconds())}`
}

function formatUtcTimestamp(date: Date) {
  return `${date.getUTCFullYear()}${pad(date.getUTCMonth() + 1)}${pad(date.getUTCDate())}T${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}Z`
}

function buildRecurrenceRule(recurrence: IcsRecurrence) {
  const values = [`FREQ=${recurrence.frequency}`]
  if (recurrence.interval && recurrence.interval > 1) values.push(`INTERVAL=${Math.floor(recurrence.interval)}`)
  if (recurrence.count && recurrence.count > 0) values.push(`COUNT=${Math.floor(recurrence.count)}`)
  if (recurrence.until) values.push(`UNTIL=${formatUtcTimestamp(recurrence.until)}`)
  return `RRULE:${values.join(';')}`
}

function escapeIcsText(value: string) {
  return value
    .replace(/\\/g, '\\\\')
    .replace(/\r?\n/g, '\\n')
    .replace(/,/g, '\\,')
    .replace(/;/g, '\\;')
}

/** RFC 5545 folds content lines at 75 UTF-8 octets, not JavaScript characters. */
function foldIcsLine(line: string) {
  const encoder = new TextEncoder()
  const chunks: string[] = []
  let chunk = ''
  let byteLimit = 75

  for (const character of line) {
    if (encoder.encode(chunk + character).length > byteLimit && chunk) {
      chunks.push(chunk)
      chunk = character
      byteLimit = 74
    } else {
      chunk += character
    }
  }
  chunks.push(chunk)
  return chunks.map((value, index) => index === 0 ? value : ` ${value}`).join('\r\n')
}

function makeStableUid(event: IcsCalendarEvent, groupId: string) {
  return `${formatTimestamp(event.start, event.timeMode ?? 'local')}-${slug(event.title)}@${groupId.toLowerCase()}`
}

function sanitizeUid(uid: string) {
  return uid.replace(/[\r\n]/g, '').trim() || 'event@athan-pwa'
}

function withUidSuffix(uid: string, count: number) {
  const at = uid.lastIndexOf('@')
  return at > 0 ? `${uid.slice(0, at)}-${count}${uid.slice(at)}` : `${uid}-${count}`
}

function normalizeReminder(minutes: number) {
  return Number.isFinite(minutes) ? Math.max(0, Math.floor(minutes)) : DEFAULT_REMINDER_MIN
}

function slug(value: string) {
  return value.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 48) || 'event'
}

function pad(value: number) {
  return String(value).padStart(2, '0')
}
