import { buildIcsCalendar, type IcsCalendarEvent } from './ics'
import { validateSecondReminder, type SecondReminderPreference } from './calendarSecondReminder'
import { formatUtcOffset, sourceWeekday, zonedWallClockToInstant } from './sourceTime'
import type { PrayerSettings } from './prayer'
import type { JumuahReminderSettings } from './iqama'
import type { SalahReminderPreferences } from './salahReminder'

export type SettingsRichSource = {
  identity: string
  locationLabel: string
  sourceLabel: string
  timezone: string
  settings: PrayerSettings
  latitude: number
  longitude: number
}

export type SettingsRichDay = {
  dateKey: string
  times: {
    fajr: Date
    sunrise: Date
    dhuhr: Date
    asr: Date
    maghrib: Date
    isha: Date
  }
}

export type SettingsRichOptions = {
  source: SettingsRichSource
  days: SettingsRichDay[]
  label: string
  reminderMinutes: number
  secondReminder: SecondReminderPreference
  fixedIshaEnabled: boolean
  fixedIshaTime: string
  jumuah: JumuahReminderSettings
  salahReview: SalahReminderPreferences
}

const PRAYERS = [
  ['fajr', 'Fajr'], ['sunrise', 'Sunrise'], ['dhuhr', 'Dhuhr'],
  ['asr', 'Asr'], ['maghrib', 'Maghrib'], ['isha', 'Isha']
] as const

export function buildSettingsRichCalendar(options: SettingsRichOptions): string {
  validateSecondReminder(options.reminderMinutes, options.secondReminder)
  if (!options.source.timezone) throw new Error('The primary source timezone is required for calendar export.')
  const events: IcsCalendarEvent[] = []
  const identity = options.source.identity.replace(/[^a-zA-Z0-9_-]+/g, '-')

  for (const day of options.days) {
    for (const [key, prayer] of PRAYERS) {
      const start = day.times[key]
      if (!(start instanceof Date) || !Number.isFinite(start.getTime())) {
        throw new Error(`No valid ${prayer} time is available for ${day.dateKey}.`)
      }
      events.push({
        title: `Athan - ${prayer}`,
        start,
        timeMode: 'utc',
        uid: `${day.dateKey}-${key}-${identity}@athan-pwa`,
        location: options.source.locationLabel,
        description: `Prayer reminder for ${prayer}. Source: ${options.source.sourceLabel}. Method: ${options.source.settings.method}. Madhab: ${options.source.settings.madhab}. High-latitude rule: ${options.source.settings.highLatRule}. Location: ${options.source.locationLabel}. Timezone: ${options.source.timezone}. Offset: ${formatUtcOffset(start, options.source.timezone)}.`,
        categories: ['Settings Athan'],
        alarms: [
          { minutesBefore: options.reminderMinutes, description: `${prayer} prayer reminder` },
          ...(options.secondReminder.enabled
            ? [{ minutesBefore: options.secondReminder.minutesBefore, description: `${prayer} prayer reminder` }]
            : [])
        ]
      })
    }

    if (options.fixedIshaEnabled) {
      const start = zonedWallClockToInstant(day.dateKey, options.fixedIshaTime, options.source.timezone)
      events.push(extraEvent('Isha Reminder (custom time)', day.dateKey, 'fixed-isha', start, identity, options.source, options.reminderMinutes))
    }

    if (options.jumuah.include && sourceWeekday(day.dateKey) === 5) {
      const start = zonedWallClockToInstant(day.dateKey, options.jumuah.time, options.source.timezone)
      events.push(extraEvent('Today is Jumu’ah', day.dateKey, 'jumuah', start, identity, options.source, 10))
    }

    if (options.salahReview.enabled) {
      const start = zonedWallClockToInstant(day.dateKey, options.salahReview.time, options.source.timezone)
      events.push(extraEvent('Review today’s Salah Tracker', day.dateKey, 'salah-review', start, identity, options.source, 0))
    }
  }

  return buildIcsCalendar(events, {
    name: `Athan — ${options.source.locationLabel} (${options.label})`,
    description: `Prayer reminders for ${options.source.locationLabel}. Source: ${options.source.sourceLabel}. Timezone: ${options.source.timezone}. Generated by Athan PWA.`,
    groupId: 'ATHAN-PWA-SETTINGS',
    defaultReminderMin: options.reminderMinutes
  })
}

function extraEvent(
  title: string,
  dateKey: string,
  eventKey: string,
  start: Date,
  identity: string,
  source: SettingsRichSource,
  minutesBefore: number
): IcsCalendarEvent {
  return {
    title,
    start,
    timeMode: 'utc',
    uid: `${dateKey}-${eventKey}-${identity}@athan-pwa`,
    location: source.locationLabel,
    description: `${title}. Source: ${source.locationLabel}. Timezone: ${source.timezone}. Calendar apps manage alert delivery.`,
    categories: ['Settings Athan'],
    alarms: [{ minutesBefore, description: title }]
  }
}

export function settingsRichFilename(source: SettingsRichSource, label: string): string {
  const safe = source.locationLabel.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '').slice(0, 40) || 'location'
  return `athan-reminders-${label}-${safe}.ics`
}
