import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import NeedHelp from './NeedHelp'

beforeEach(() => {
  Object.defineProperty(Element.prototype, 'scrollIntoView', { configurable: true, value: vi.fn() })
})

afterEach(() => { cleanup(); vi.useRealTimers(); vi.restoreAllMocks(); window.history.replaceState(null, '', '/') })

describe('Help navigation intents', () => {
  it('makes restored details searchable and the regional method table accessible without requests', () => {
    const requests = vi.spyOn(globalThis, 'fetch')
    const view = render(<NeedHelp />)
    expect(screen.getByText(/Assalamu alaikum. Need a hand/)).toBeVisible()
    fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'noon shadow' } })
    fireEvent.click(view.container.querySelector('#calculation summary')!)
    const table = screen.getByRole('table', { name: 'Calculation methods: names and regional reference points' })
    expect(within(table).getAllByRole('row')).toHaveLength(13)
    const source = screen.getByRole('link', { name: /PrayTimes: Asr calculation/ })
    expect(source).toHaveAttribute('rel', 'noopener noreferrer')
    expect(source).toHaveAttribute('href', 'https://praytimes.org/docs/calculation')
    expect(requests).not.toHaveBeenCalled()
  })
  it('shows a selectable complete conversion prompt and the warmer closing', () => {
    const view = render(<NeedHelp />)
    fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'unreadable cells' } })
    fireEvent.click(view.container.querySelector('#manual-timetable summary')!)
    expect(screen.getByLabelText('Timetable conversion prompt')).toHaveTextContent('Preserve every printed time exactly')
    fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'shoe size' } })
    fireEvent.click(view.container.querySelector('#troubleshooting summary')!)
    expect(screen.getByText(/JazakAllahu khairan for using Athan/)).toBeVisible()
    expect(screen.getByText(/neither your birthday nor your shoe size/)).toBeVisible()
  })
  it('searches guide text only, opens a topic, and navigates to its real screen without writing records', () => {
    const go = vi.fn()
    const writes = vi.spyOn(Storage.prototype, 'setItem')
    const requests = vi.spyOn(globalThis, 'fetch')
    const view = render(<NeedHelp go={go} />)
    fireEvent.change(screen.getByRole('searchbox', { name: 'Search this guide' }), { target: { value: 'star(3-5)' } })
    expect(screen.getByRole('status')).toHaveTextContent('1 help topic matches')
    const topic = view.container.querySelector('#salah-search') as HTMLDetailsElement
    expect(topic.open).toBe(false)
    fireEvent.click(topic.querySelector('summary')!)
    expect(topic.open).toBe(true)
    fireEvent.click(within(topic).getByRole('button', { name: 'Open Search Salah Progress' }))
    expect(go).toHaveBeenCalledWith('SalahSearch')
    fireEvent.click(within(topic).getByRole('button', { name: 'Back to help topics' }))
    expect(screen.getByRole('searchbox')).toHaveFocus()
    expect(writes).not.toHaveBeenCalled()
    expect(requests).not.toHaveBeenCalled()
  })
  it('has a reversible empty guide search and expands/collapses topics without record changes', () => {
    const view = render(<NeedHelp />)
    fireEvent.click(screen.getByRole('button', { name: 'Expand listed topics' }))
    expect([...view.container.querySelectorAll('details')].every(topic => topic.open)).toBe(true)
    fireEvent.click(screen.getByRole('button', { name: 'Collapse all topics' }))
    expect([...view.container.querySelectorAll('details')].every(topic => !topic.open)).toBe(true)
    fireEvent.change(screen.getByRole('searchbox'), { target: { value: 'nonexistent-guide-topic-xyz' } })
    expect(screen.getByText(/No matching help topics/)).toBeVisible()
    fireEvent.click(screen.getByRole('button', { name: 'Clear guide search' }))
    expect(view.container.querySelector('#getting-started')).not.toBeNull()
  })
  it('retains legacy topic links and supports repeated topic jumps without changing shared URLs', () => {
    vi.useFakeTimers()
    window.history.replaceState(null, '', '/#methods')
    const scroll = vi.fn()
    Object.defineProperty(Element.prototype, 'scrollIntoView', { configurable: true, value: scroll })
    const view = render(<NeedHelp />)
    vi.runAllTimers()
    expect((view.container.querySelector('#calculation') as HTMLDetailsElement).open).toBe(true)
    expect(document.getElementById('help-title-calculation')).toHaveFocus()
    const jump = within(screen.getByRole('navigation', { name: 'Help topics' })).getByRole('button', { name: 'Prayer source, city time and travel' })
    fireEvent.click(jump)
    vi.runAllTimers()
    fireEvent.click(jump)
    vi.runAllTimers()
    expect(scroll).toHaveBeenCalledTimes(3)
    expect(window.location.hash).toBe('#methods')
  })
  it('opens the Qibla section without overwriting a shared-defaults fragment', () => {
    vi.useFakeTimers()
    window.history.replaceState(null, '', '/#share-defaults=test')
    const scroll = vi.fn()
    Object.defineProperty(Element.prototype, 'scrollIntoView', { configurable: true, value: scroll })
    render(<NeedHelp navigationIntent={{ screen: 'NeedHelp', section: 'qibla' }} />)
    vi.runAllTimers()
    expect(scroll).toHaveBeenCalledOnce()
    expect(window.location.hash).toBe('#share-defaults=test')
  })

  it('cancels pending anchor work when leaving the help screen', () => {
    vi.useFakeTimers()
    const scroll = vi.fn()
    Object.defineProperty(Element.prototype, 'scrollIntoView', { configurable: true, value: scroll })
    const view = render(<NeedHelp navigationIntent={{ screen: 'NeedHelp', section: 'qibla' }} />)
    view.unmount()
    vi.runAllTimers()
    expect(scroll).not.toHaveBeenCalled()
  })
  it('shows safe read-only Qibla diagnostics even if its saved snapshot has malformed fields', () => {
    const read = vi.spyOn(Storage.prototype, 'getItem').mockReturnValue(JSON.stringify({
      compassStatus: { invalid: true }, locationStatus: [], bearing: 'not a bearing', headingSource: 'unknown',
    }))
    const writes = vi.spyOn(Storage.prototype, 'setItem')
    const view = render(<NeedHelp />)
    fireEvent.click(view.container.querySelector('#qibla summary')!)
    expect(screen.getByText('Last-recorded Qibla status')).toBeVisible()
    expect(screen.getByText('No absolute heading recorded')).toBeVisible()
    expect(screen.getByText('Open Qibla to calculate')).toBeVisible()
    expect(read).toHaveBeenCalledWith('athan.qibla.status.v1')
    expect(writes).not.toHaveBeenCalled()
  })
})
